x = input('Digite algo: ')
print('Tem algo escrito? {}'.format(bool(x)))
print('Qual o tipo? {}'.format(type(x)))
print('Possui números ou letras? {}'.format(x.isalnum()))
print('É um número ? {}'.format(x.isnumeric()))
print('Possui letras? {} '.format(x.isalpha()))
print('Apenas possui letras minúsculas? {} '.format(x.islower()))
print('Apenas possui letras maiúsculas? {}'.format(x.isupper()))
print('Tem letras maiúsculas e minúsculas (capitalizada)? {}'.format(x.istitle()))